var annotated_dup =
[
    [ "ball_order", "structball__order.html", "structball__order" ],
    [ "ball_t", "classball__t.html", "classball__t" ],
    [ "genealogy_t", "classgenealogy__t.html", "classgenealogy__t" ],
    [ "inventory_t", "classinventory__t.html", "classinventory__t" ],
    [ "lbdp_parameters_t", "structlbdp__parameters__t.html", "structlbdp__parameters__t" ],
    [ "lbdp_state_t", "structlbdp__state__t.html", "structlbdp__state__t" ],
    [ "master_t", "classmaster__t.html", "classmaster__t" ],
    [ "moran_parameters_t", "structmoran__parameters__t.html", "structmoran__parameters__t" ],
    [ "moran_state_t", "structmoran__state__t.html", "structmoran__state__t" ],
    [ "node_t", "classnode__t.html", "classnode__t" ],
    [ "nodeseq_t", "classnodeseq__t.html", "classnodeseq__t" ],
    [ "pocket_t", "classpocket__t.html", "classpocket__t" ],
    [ "popul_proc_t", "classpopul__proc__t.html", "classpopul__proc__t" ],
    [ "s2i2r2_parameters_t", "structs2i2r2__parameters__t.html", "structs2i2r2__parameters__t" ],
    [ "s2i2r2_state_t", "structs2i2r2__state__t.html", "structs2i2r2__state__t" ],
    [ "seir_parameters_t", "structseir__parameters__t.html", "structseir__parameters__t" ],
    [ "seir_state_t", "structseir__state__t.html", "structseir__state__t" ],
    [ "si2r_parameters_t", "structsi2r__parameters__t.html", "structsi2r__parameters__t" ],
    [ "si2r_state_t", "structsi2r__state__t.html", "structsi2r__state__t" ],
    [ "siir_parameters_t", "structsiir__parameters__t.html", "structsiir__parameters__t" ],
    [ "siir_state_t", "structsiir__state__t.html", "structsiir__state__t" ],
    [ "sir_parameters_t", "structsir__parameters__t.html", "structsir__parameters__t" ],
    [ "sir_state_t", "structsir__state__t.html", "structsir__state__t" ]
];